### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by eddsalkield** [NomisIV/swayhide#6]
Firstly, thanks so much for your work on this project!
I'd love to package it for the alpine linux repos, but in order to do so I need to clarify that this is free software.  Would you be willing to pick a license and put it on the repo?  GPLv3+ or MIT might be good choices :)

**Comment by NomisIV** [comment]
Thanks for reaching out! This project is now licensed under GPL 3.0.
Also, thanks for packaging the swayhide for alpine! :)

**Comment by eddsalkield** [comment]
Brilliant thanks - the package has now hit Alpine Edge :)
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/33081
