### ISSUE TITLE
Compiling on aarch64/musl

### ISSUE THREAD

**Issue by 101313** [NomisIV/swayhide#7]
Hey there, I tried installing with both cargo as well as compiling the source but I get greeted with the following message:

```
error: failed to compile `swayhide v0.2.1 (/root/swayhide)`, intermediate artifacts can be found at `/root/swayhide/target`

Caused by:
  cannot produce proc-macro for `failure_derive v0.1.8` as the target `aarch64-unknown-linux-musl` does not support these crate types
```

Been wondering if proc-macro is any easy to substitute with an alternative so I could maybe get it running on my machine.

**Comment by NomisIV** [comment]
Hey! I'm sorry for the late reply.
Unfortunately this is out of my reach, and if you want any progress you'll have to ask [swayipc](https://github.com/jaycefayne/swayipc-rs) upstream for aarch-musl support. Once that's merged (or on the way), feel free to reopen this issue.
But for now, there's nothing I can do :(
