### ISSUE TITLE
Continuation of Development

### ISSUE THREAD

**Issue by rehanzo** [NomisIV/swayhide#9]
Hey!

I currently use sway and have prior experience with rust, and would be willing to take over development/maintenance of the repo.

**Comment by NomisIV** [comment]
Great! I will transfer the repo to you!

@WhyNotHugo Could you update the AUR package to reflect this?

**Comment by WhyNotHugo** [comment]
Ping me when there's a stable release and I'll update the package, there's not much to do in the meantime.

**Comment by rehanzo** [comment]
Great, hope to continue development long into the future!
